language: node_js

node_js:
  - "stable"

services:
  - docker

before_deploy: 
  - docker build -t tradeforgoals/frontend .
  - docker run -d -p 80:3001 tradeforgoals/frontend
  - docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
