language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run tslint
before_deploy: 
  - ./before_deploy.sh
deploy:
  provider: azure_web_apps
  verbose: true