language: node_js

node_js:
  - "11.14.0"

services:
  - docker

install:
  - npm install

before_deploy: 
  - docker build -t tradeforgoals.azurecr.io/tradeforgoals/frontend .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

addons:
  sonarcloud:
    organization: "tradeforgoals"
    token:
      secure: "$SONAR_TOKEN"
script:
  - npm run tslint-report && npm run test-report && sonar-scanner