services:
  - docker

before_deploy: 
  - docker build -t tradeforgoals/frontend .
  - docker run -d -p 80:3001 tradeforgoals/frontend
  - docker ps -a

deploy:
  provider: azure_web_apps
  verbose: true